- name: "Create superuser for the project in targeted server(s)"
  hosts: all

  vars_prompt:
    - name: superuser_email
      prompt: Enter superuser email?
      private: no

    - name: superuser_password
      prompt: Enter superuser password?

  roles:
    - { role: superuser }
