# NOTE: This command only works on Django 3.0+

- name: "Create Django superuser"
  command: >-
    docker-compose
    run
    -e DJANGO_SUPERUSER_EMAIL
    -e DJANGO_SUPERUSER_PASSWORD
    --rm django python manage.py createsuperuser --no-input
  environment:
    DJANGO_SUPERUSER_EMAIL: "{{ "{{ superuser_email }}" }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ "{{ superuser_password }}" }}"
  args:
    chdir: "{{ "{{ code_dir }}" }}"
  register: result


- debug:
    var: result
