# You can also use the fallback image from docker hub: thorgate/django-template-ci:latest
image: registry.gitlab.com/thorgate-public/django-project-template/ci:latest

services:
  - docker:dind

variables:
  POSTGRES_USER: "{{ cookiecutter.repo_name }}"
  POSTGRES_PASSWORD: "{{ cookiecutter.repo_name }}"
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: "1"
  COMPOSE_DOCKER_CLI_BUILD: "1"

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

stages:
  - test
{%- if cookiecutter.frontend_style == 'spa' %}
  - build
{%- endif %}
  - bump-version

test:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  except:
    - template # Don't run CI on template branch, should not be required
  variables:
    EDIT_SETTINGS: "no"
  script:
    - make settings
    - docker-compose build
    - make node-install
    - make quality
    - make coverage

{%- if cookiecutter.frontend_style == 'spa' %}

build:
  stage: build
  except:
    - template # Don't run CI on template branch, should not be required
  script:
    - EDIT_SETTINGS=no make settings
    # Ensure production images build also
    - docker-compose -f docker-compose.production.yml build{% endif %}

# IMPORTANT! You need to setup repository and git keys to use it!
# 1. Generate new key: ssh-keygen -t ecdsa -b 521 -C '{{ cookiecutter.project_title }}' -f id_ecdsa
# 2. Copy public key: cat id_ecdsa.pub
# 3. Go to your_project_name → Settings → Repository → Deploy Keys, paste public key,
#   select "Write access allowed", click add
# 4. Add new protected CI/CD variable with name 'GIT_KEY' and content from: base64 -i id_ecdsa
Bump version & tag:
  image: python:3.8-buster
  stage: bump-version
  variables:
    GIT_SSH_COMMAND: 'ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null'
  before_script:
    - mkdir -p ~/.ssh
    - echo $GIT_KEY | base64 -d > ~/.ssh/id_ecdsa
    - chmod 400 ~/.ssh/id_ecdsa
    - git config --global user.email "thorgatebot@thorgate.eu"
    - git config --global user.name "Thorgate Bot"
    - pip install bump2version
  script:
    - git remote set-url origin git@gitlab.com:${CI_PROJECT_PATH}.git
    - git checkout master
    - git pull origin master
    - bump2version patch
    - git push --follow-tags
  except:
    variables:
      - '$CI_COMMIT_MESSAGE =~ /Bump version: v/'
      - '$CI_COMMIT_MESSAGE =~ /bump-ignore/'
  only:
    - master
